dist: trusty
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.15.0

before_install:
  # Docker Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker-compose up --build -d

script:
  - exit 0

after_script:
  - docker-compose down